
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jackson:
    mapper:
      accept-case-insensitive-enums: true
    date-format: "dd/MM/yyyy"
    serialization:
      write-dates-as-timestamps: false
  messages:
    basename: messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  cache:
    type: redis
  data:
    redis:
      port: 6674
      host: localhost
