name: 'JAVA CI'

on:
  pull_request:
    branches:
      - main
#  schedule:
#    - '0 12 * * *' #auto execute at 12 a.m
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        java: [ 17 ]

    runs-on: ${{matrix.os}}

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          DB_DATABASE: user_travel_v1
          DB_USER: ${{secrets.DB_USERNAME_DEV_ENV}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD_DEV_ENV}}
          DB_ROOT_PASSWORD: ${{secrets.DB_PASSWORD_DEV_ENV}}
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-timeout=5s
          --health-interval=10s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{matrix.java}}

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{matrix.os}}-maven-${{hashFiles('**/pom.xml')}}
          restore-keys: |
            ${{matrix.os}}-maven-

      - name: Maven Build
        env:
          DB_URL: ${{secrets.DB_URL_DEV_ENV}}
          DB_USERNAME: ${{secrets.DB_USERNAME_DEV_ENV}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD_DEV_ENV}}
          CLOUDINARY_CLOUD_NAME: ${{secrets.CLOUDINARY_CLOUD_NAME}}
          CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
          CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
        run: mvn --batch-mode --fail-at-end clean install

      - name: Upload file JAR
        if: success() #Only upload if maven build success
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar