name: 'JAVA CI'

on:
  pull_request:
    branches: [ main ]
#  schedule:
#    - '0 12 * * *' #auto execute at 12 a.m
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 17 ]
    outputs:
      os: ${{matrix.os}}
      java: ${{matrix.java}}

    timeout-minutes: 15 #15mins to cancel, dont' crack
    runs-on: ${{matrix.os}}

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: user_travel_v1
          MYSQL_USER: test
          MYSQL_PASSWORD: 123456
          MYSQL_ROOT_PASSWORD: 123456
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-timeout=5s
          --health-interval=10s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{matrix.java}}

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{matrix.os}}-maven-${{hashFiles('**/pom.xml')}}
          restore-keys: |
            ${{matrix.os}}-maven-

      - name: Maven Build
        env:
          DB_URL: ${{secrets.DB_URL_DEV_ENV}}
          DB_USERNAME: ${{secrets.DB_USERNAME_DEV_ENV}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD_DEV_ENV}}
          CLOUDINARY_CLOUD_NAME: ${{secrets.CLOUDINARY_CLOUD_NAME}}
          CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
          CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
        run: mvn --batch-mode --fail-at-end clean install -DskipTests

      - name: Upload file JAR
        if: success() #Only upload if maven build success
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

#      - name: Create Github Releases
#        uses: softprops/action-gh-release@v1
#        with:
#          name: Release ${{github.ref_name}}
#          tag_name: ${{github.ref_name}}
#          files: target/*.jar
#        env:
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  deploy:
    needs: build
    runs-on: ${{needs.build.outputs.os}}
    if: github.ref_name == 'refs/heads/main'

    steps:
      - name: Deploy to Render
        run: curl -X POST ${{secrets.RENDER_DEPLOY_HOOK}}



#  create-pr:
#    runs-on: ${{matrix.os}}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Create pull request
#        uses: peter-evans/create-pull-request@v5
#        with:
#          token: '${{ github.token }}'
#          base: main
#          branch: ${{github.ref_name}}
#          title: Auto PR from ${{github.ref_name}}
#          body: 'Automated changes by [create-pull-request] GitHub action'